Add cut & scale options & update help

diff --git a/reduce_video_filesize b/reduce_video_filesize
--- a/reduce_video_filesize
+++ b/reduce_video_filesize
@@ -1,24 +1,41 @@
 #!/bin/bash
 
-file="$1"
-
-if [ $# -lt 1 ] || ! [ -f "$file" ]; then
-	echo "Usage: $0 <input_file> [<start_at>] [<additional_ffmpeg_args>]"
+help() {
+	echo "Usage: $0 [-s] [-c <start_at>] <input_file>"
 	echo -e "\tReencodes <input_file> to reduce filesize, copying all tracks"
 	echo -e "\tMay not accept unix or windows style paths (not implemented)"
-	echo -e "\tOptionally cut everything before the timestamp <start_at> (hh:mm:ss.xxx)."
-	echo -e "\t\tTo pass additional args without cutting, pass an invalid format, e.g. empty string"
+	echo -e "\t-c <start_at>: cut everything before the timestamp <start_at> (hh:mm:ss.xxx)"
+	echo -e "\t-s: scale to 720p"
 	exit
-fi
+}
 
+for arg in "$@"; do
+	( [[ "$arg" == "-h" ]] || [[ "$arg" == "--help" ]] ) && help
+done
 
 start_timestamp=""
-if [[ $2 =~ ^[0-9]+(:[0-9]{2}){2}[.][0-9]{3}$ ]]; then
-	start_timestamp="-ss $2"
-	shift
-fi
+scale=""
+while getopts ":c:s" opt; do
+	case "$opt" in
+	c)
+		[[ $OPTARG =~ ^[0-9]+(:[0-9]{2}){2}[.][0-9]{3}$ ]] || help
+		start_timestamp="-ss $OPTARG"
+		;;
+	s)
+		scale="-vf scale=1280:-1"
+		;;
+	*)
+		help
+		;;
+	
+	esac
+done
+shift $((OPTIND-1))
+[[ $# -eq 1 ]] || help
 
-shift
+
+file="$1"
+[[ -f "$file" ]] || { echo "Error: Input file does not exist"; exit; }
 
 bak="${file%.*}.bak.${file##*.}"
 temp="${file%.*}.temp.mkv"
@@ -28,7 +45,7 @@ if [ -f "$bak" ] || [ -f "$temp" ]; then
 	exit
 fi
 
-ffmpeg $start_timestamp -i "$file" $@ -c:v libx265 -crf 19 -preset slow -map 0 "$temp"
+ffmpeg $start_timestamp -i "$file" $scale -c:v libx265 -crf 19 -preset slow -map 0 "$temp"
 
 if ! [ -f "$temp" ]; then
 	echo "Reencode failed ... exiting"
